# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ravi/devel/tools/clion-2017.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/ravi/devel/tools/clion-2017.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ravi/projects/iot-dsa-v2/engine.io

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ravi/projects/iot-dsa-v2/engine.io

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ravi/devel/tools/clion-2017.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ravi/devel/tools/clion-2017.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ravi/projects/iot-dsa-v2/engine.io/CMakeFiles /home/ravi/projects/iot-dsa-v2/engine.io/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ravi/projects/iot-dsa-v2/engine.io/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named engine_io

# Build rule for target.
engine_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 engine_io
.PHONY : engine_io

# fast build rule for target.
engine_io/fast:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/build
.PHONY : engine_io/fast

core/src/engine.io.o: core/src/engine.io.cpp.o

.PHONY : core/src/engine.io.o

# target to build an object file
core/src/engine.io.cpp.o:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/engine.io.cpp.o
.PHONY : core/src/engine.io.cpp.o

core/src/engine.io.i: core/src/engine.io.cpp.i

.PHONY : core/src/engine.io.i

# target to preprocess a source file
core/src/engine.io.cpp.i:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/engine.io.cpp.i
.PHONY : core/src/engine.io.cpp.i

core/src/engine.io.s: core/src/engine.io.cpp.s

.PHONY : core/src/engine.io.s

# target to generate assembly for a file
core/src/engine.io.cpp.s:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/engine.io.cpp.s
.PHONY : core/src/engine.io.cpp.s

core/src/operating-context.o: core/src/operating-context.cpp.o

.PHONY : core/src/operating-context.o

# target to build an object file
core/src/operating-context.cpp.o:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/operating-context.cpp.o
.PHONY : core/src/operating-context.cpp.o

core/src/operating-context.i: core/src/operating-context.cpp.i

.PHONY : core/src/operating-context.i

# target to preprocess a source file
core/src/operating-context.cpp.i:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/operating-context.cpp.i
.PHONY : core/src/operating-context.cpp.i

core/src/operating-context.s: core/src/operating-context.cpp.s

.PHONY : core/src/operating-context.s

# target to generate assembly for a file
core/src/operating-context.cpp.s:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/operating-context.cpp.s
.PHONY : core/src/operating-context.cpp.s

core/src/platform-config.o: core/src/platform-config.cpp.o

.PHONY : core/src/platform-config.o

# target to build an object file
core/src/platform-config.cpp.o:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/platform-config.cpp.o
.PHONY : core/src/platform-config.cpp.o

core/src/platform-config.i: core/src/platform-config.cpp.i

.PHONY : core/src/platform-config.i

# target to preprocess a source file
core/src/platform-config.cpp.i:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/platform-config.cpp.i
.PHONY : core/src/platform-config.cpp.i

core/src/platform-config.s: core/src/platform-config.cpp.s

.PHONY : core/src/platform-config.s

# target to generate assembly for a file
core/src/platform-config.cpp.s:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/platform-config.cpp.s
.PHONY : core/src/platform-config.cpp.s

core/src/platform-linux.o: core/src/platform-linux.cpp.o

.PHONY : core/src/platform-linux.o

# target to build an object file
core/src/platform-linux.cpp.o:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/platform-linux.cpp.o
.PHONY : core/src/platform-linux.cpp.o

core/src/platform-linux.i: core/src/platform-linux.cpp.i

.PHONY : core/src/platform-linux.i

# target to preprocess a source file
core/src/platform-linux.cpp.i:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/platform-linux.cpp.i
.PHONY : core/src/platform-linux.cpp.i

core/src/platform-linux.s: core/src/platform-linux.cpp.s

.PHONY : core/src/platform-linux.s

# target to generate assembly for a file
core/src/platform-linux.cpp.s:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/platform-linux.cpp.s
.PHONY : core/src/platform-linux.cpp.s

core/src/platform.o: core/src/platform.cpp.o

.PHONY : core/src/platform.o

# target to build an object file
core/src/platform.cpp.o:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/platform.cpp.o
.PHONY : core/src/platform.cpp.o

core/src/platform.i: core/src/platform.cpp.i

.PHONY : core/src/platform.i

# target to preprocess a source file
core/src/platform.cpp.i:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/platform.cpp.i
.PHONY : core/src/platform.cpp.i

core/src/platform.s: core/src/platform.cpp.s

.PHONY : core/src/platform.s

# target to generate assembly for a file
core/src/platform.cpp.s:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/platform.cpp.s
.PHONY : core/src/platform.cpp.s

core/src/stream.io-uv.o: core/src/stream.io-uv.cpp.o

.PHONY : core/src/stream.io-uv.o

# target to build an object file
core/src/stream.io-uv.cpp.o:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/stream.io-uv.cpp.o
.PHONY : core/src/stream.io-uv.cpp.o

core/src/stream.io-uv.i: core/src/stream.io-uv.cpp.i

.PHONY : core/src/stream.io-uv.i

# target to preprocess a source file
core/src/stream.io-uv.cpp.i:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/stream.io-uv.cpp.i
.PHONY : core/src/stream.io-uv.cpp.i

core/src/stream.io-uv.s: core/src/stream.io-uv.cpp.s

.PHONY : core/src/stream.io-uv.s

# target to generate assembly for a file
core/src/stream.io-uv.cpp.s:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/stream.io-uv.cpp.s
.PHONY : core/src/stream.io-uv.cpp.s

core/src/systembus.o: core/src/systembus.cpp.o

.PHONY : core/src/systembus.o

# target to build an object file
core/src/systembus.cpp.o:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/systembus.cpp.o
.PHONY : core/src/systembus.cpp.o

core/src/systembus.i: core/src/systembus.cpp.i

.PHONY : core/src/systembus.i

# target to preprocess a source file
core/src/systembus.cpp.i:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/systembus.cpp.i
.PHONY : core/src/systembus.cpp.i

core/src/systembus.s: core/src/systembus.cpp.s

.PHONY : core/src/systembus.s

# target to generate assembly for a file
core/src/systembus.cpp.s:
	$(MAKE) -f CMakeFiles/engine_io.dir/build.make CMakeFiles/engine_io.dir/core/src/systembus.cpp.s
.PHONY : core/src/systembus.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... engine_io"
	@echo "... core/src/engine.io.o"
	@echo "... core/src/engine.io.i"
	@echo "... core/src/engine.io.s"
	@echo "... core/src/operating-context.o"
	@echo "... core/src/operating-context.i"
	@echo "... core/src/operating-context.s"
	@echo "... core/src/platform-config.o"
	@echo "... core/src/platform-config.i"
	@echo "... core/src/platform-config.s"
	@echo "... core/src/platform-linux.o"
	@echo "... core/src/platform-linux.i"
	@echo "... core/src/platform-linux.s"
	@echo "... core/src/platform.o"
	@echo "... core/src/platform.i"
	@echo "... core/src/platform.s"
	@echo "... core/src/stream.io-uv.o"
	@echo "... core/src/stream.io-uv.i"
	@echo "... core/src/stream.io-uv.s"
	@echo "... core/src/systembus.o"
	@echo "... core/src/systembus.i"
	@echo "... core/src/systembus.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

